final

diff --git a/.github/workflows/dev-pipeline.yml b/.github/workflows/dev-pipeline.yml
--- a/.github/workflows/dev-pipeline.yml
+++ b/.github/workflows/dev-pipeline.yml
@@ -151,24 +151,24 @@ jobs:
           pip install selenium webdriver-manager
           python3 apps/${{ matrix.app }}/app_tests.py ${{ steps.provision.outputs.linode-info }}
 
-      - name: deleting linode for ${{ matrix.app }} app
-        if: always()
-        run: |
-          set -e
-          LINODE_ID=$(jq -r '.id' response.json)
-          if [ -n "$LINODE_ID" ] && [ "$LINODE_ID" != "null" ]; then
-            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE \
-              -H "Authorization: Bearer ${{ secrets.LINODE_API_SECRET }}" \
-              https://api.linode.com/v4/linode/instances/$LINODE_ID)
-            if [ "$RESPONSE" = "200" ]; then
-              echo "Linode $LINODE_ID deleted successfully."
-            else
-              echo "Failed to delete Linode $LINODE_ID. Status code: $RESPONSE"
-              exit 1
-            fi
-          else
-            echo "No Linode ID found to delete."
-          fi
+#      - name: deleting linode for ${{ matrix.app }} app
+#        if: always()
+#        run: |
+#          set -e
+#          LINODE_ID=$(jq -r '.id' response.json)
+#          if [ -n "$LINODE_ID" ] && [ "$LINODE_ID" != "null" ]; then
+#            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE \
+#              -H "Authorization: Bearer ${{ secrets.LINODE_API_SECRET }}" \
+#              https://api.linode.com/v4/linode/instances/$LINODE_ID)
+#            if [ "$RESPONSE" = "200" ]; then
+#              echo "Linode $LINODE_ID deleted successfully."
+#            else
+#              echo "Failed to delete Linode $LINODE_ID. Status code: $RESPONSE"
+#              exit 1
+#            fi
+#          else
+#            echo "No Linode ID found to delete."
+#          fi
 
   notify-results:
     name: providing results
